steps:
  # 깃 샤값을 기반으로 이미지의 존재 여부를 확인하는 스텝
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'check-git-sha-tag'
    entrypoint: 'bash'
    args:
    - '-c'
    - |
      echo "SHORT_SHA: $SHORT_SHA"
      a_IMAGE_EXISTS2=$(gcloud container images list-tags gcr.io/swit-ops/test-img)
      echo "IMAGE_EXISTS2: $a_IMAGE_EXISTS2"
  #     if [[ $IMAGE_EXISTS2 == *"$SHORT_SHA"* ]]; then
  #       echo "Image with git SHA tag already exists. Proceeding to tag."
  #     else
  #       echo "No image found with git SHA tag. Proceeding with build."
  #     fi

  # # 이미지 빌드 및 푸시 스텝
  # - name: 'gcr.io/kaniko-project/executor:latest'
  #   id: 'build-and-push'
  #   args:
  #   - --dockerfile=deployments/Dockerfile
  #   - --destination=gcr.io/swit-ops/test-img:$BRANCH_NAME:$SHORT_SHA
  #   - --destination=us-docker.pkg.dev/swit-ops/test-231019/test-img:$BRANCH_NAME:$SHORT_SHA
  #   - --cache=false

options:
  machineType: 'N1_HIGHCPU_8'