steps:
  # 깃 샤값을 기반으로 이미지의 존재 여부를 확인하는 스텝
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'check-git-sha-tag'
    entrypoint: 'bash'
    args:
    - '-c'
    - |
      IMAGE_EXISTS=$(gcloud container images list-tags gcr.io/swit-ops/test-img --filter="tags=$SHORT_SHA" --format="get(tags)")
      if [[ $IMAGE_EXISTS == *"$SHORT_SHA"* ]]; then
        echo "Image with git SHA tag already exists. Proceeding to tag."
      else
        echo "No image found with git SHA tag. Proceeding with build."
        exit 1
      fi
  # 이미지에 시멘틱 태그 추가 스텝
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'add-semantic-tag'
    args:
    - container
    - images
    - add-tag
    - gcr.io/swit-ops/test-img:$BRANCH_NAME:$SHORT_SHA
    - gcr.io/swit-ops/test-img:$BRANCH_NAME:$TAG_NAME

options:
  machineType: 'N1_HIGHCPU_8'
substitutions:
  _SHORT_SHA: COMMIT_SHA
